name: Master

on: [push, pull_request, release]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        version: 2.6.x
    - name: Set up environment
      run: |
        gem install bundler
        bundle install
    - name: Test
      run: rake
    - name: Publish to Rubygems
      if: contains(github.ref, 'refs/tags/v')
      uses: cadwallion/publish-rubygems-action@v1.0.0
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
        RELEASE_COMMAND: rake release
